//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5contect.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_2
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Shipping_Destination { get; set; }
        public string type_or_Product { get; set; }
        public Nullable<int> approx_product_quantity { get; set; }
        public string url { get; set; }
        public string Are_you_selling_this_product_already { get; set; }
    }
}
